/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideNav: typeof import('./components/AsideNav/Index.vue')['default']
    ContextMenu: typeof import('./components/context-menu.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyPage: typeof import('./components/EmptyPage/Index.vue')['default']
    ImgList: typeof import('./components/ImgList/Index.vue')['default']
    ImgListHorizontal: typeof import('./components/ImgListHorizontal/Index.vue')['default']
    ImgPlus: typeof import('./components/ImgPlus/Index.vue')['default']
    ImgView: typeof import('./components/ImgView/Index.vue')['default']
    NavStuats: typeof import('./components/NavStuats/Index.vue')['default']
    OneTitle: typeof import('./components/OneTitle/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchList: typeof import('./components/SearchList/Index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
